### ISSUE TITLE
Swiping to both sides

### ISSUE THREAD

**Issue by ResoDev** [Purvik/SwipeTo#1]
Hello!

I'd like to make a feature request which would make this package THAT much more useful. Currently, it's possible to swipe to one side which is great but many apps would benefit from being able to swipe to both sides simultaneously.

My proposed API would be to have two swipe callbacks, let's say `onLeftSwipe` and `onRightSwipe`. If a given callback is given a value in the constructor, then swiping to that side would be made possible.

Of course, this would require to duplicate the other fields and constructor parameters as well - one for the left icon, another for the right one.

**Comment by Purvik** [comment]
@ResoDev Yes we can have this feature.
