### ISSUE TITLE
how to change the color or transition between swipe it shows some back screen.

### ISSUE THREAD

**Issue by ramsmart-inno** [Purvik/SwipeTo#12]

**Comment by Purvik** [comment]
@ramsmart-inno  Can you provide me more details on it?

**Comment by Purvik** [comment]
@ramsmart-inno  Would you be able to provide more information here by this week so can be improved? Otherwise will close this reported issue. Thanks.

**Comment by Purvik** [comment]
Closing it now as not having enough details to look into. Will reopen if have more details.
