### ISSUE TITLE
Left Swipe Not Provided 

### ISSUE THREAD

**Issue by danghanh99** [Purvik/SwipeTo#16]
[log] Left Swipe Not Provided 
![a2](https://user-images.githubusercontent.com/58250068/168207361-f0bc5998-5d7e-4edd-a172-0aa0d9c81b2e.png)
[log] Right Swipe Not Provided

**Comment by ArjunBhilare** [comment]
Did you resolve this issue?

**Comment by BawazierMurphy** [comment]
i have this issue too, the callback are not called instead it only log ([log] Left Swipe Not Provided)

**Comment by BawazierMurphy** [comment]
> i have this issue too, the callback are not called instead it only log ([log] Left Swipe Not Provided)

nevermind i solved it, just re run flutter and everything will be fine

**Comment by Purvik** [comment]
No need to take any action on this. Hence closing. Let me know if this is still occuring and need to be checked.
