### ISSUE TITLE
Get position so i can traverse to a chat reply in flutter

### ISSUE THREAD

**Issue by benthemobileguy** [Purvik/SwipeTo#17]
Just like whatapp, i need to tap on a replied message to navigate to the message i replied to in the list. But the Swipe To widget does not make available the position of a swiped item. How can it be done?

**Comment by tusharbhambere** [comment]
Just Add UniqueKey() in Key .

Just Like this =>
 SwipeTo(
              key: UniqueKey(),

Hope it will Solve Your Problem

**Comment by benthemobileguy** [comment]
Yes it does

**Comment by Purvik** [comment]
Cool. Thanks for it . Closing this out now.
