### ISSUE TITLE
Swipe to 'start'/'end' based on Localization RTL/LTR

### ISSUE THREAD

**Issue by magillus** [Purvik/SwipeTo#2]
Maybe we can add additional `SwipeDirection` - `SwipeDirection.start`; `SwipeDirection.end`

Based on LTR RTL direction of the Flutter Localization use the direction needed.

**Comment by Purvik** [comment]
@magillus  Sure. Will be checking on this one.

**Comment by watery-desert** [comment]
@magillus [this package](https://github.com/watery-desert/swipeable_tile) supports RTL until `SwipeTo` gets this feature you can use it.

**Comment by Purvik** [comment]
@magillus  Would it be possible from you to provide more details, what is expected for Directionality support? Looking into that requirement now.

**Comment by Purvik** [comment]
From updated version, `swipeDirection` been removed and can be handled by callback `onLeftSwipe` and `onRightSwipe` we're passing to enable swipe on specific direction.

**Comment by magillus** [comment]
> @magillus Would it be possible from you to provide more details, what is expected for Directionality support? Looking into that requirement now.

That is long time ago, I do not remember use-case to give details.
